### ISSUE TITLE
快速点击目录折叠展开时直接崩溃

### ISSUE THREAD

**Issue by AaronZhang0701** [JavenZ/ZJTableViewManager#10]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete row 145 from section 0 which only contains 58 rows before the update'

**Comment by jzhang0480** [comment]
看报错应该是你实际项目里用的时候出的问题吧，抽个demo出来我看看
jzhang0480@outlook.com
