### ISSUE TITLE
cellDidAppear() 中执行  item.updateHeight()无效

### ISSUE THREAD

**Issue by cuibeihong** [JavenZ/ZJTableViewManager#2]
首先，很好用的组件，感谢🙏
我的场景：自定义ZJTableViewCell子类，有一个textView，要求输入文字的时候动态修改cell的高度
问题：现在初始化item会给textView传递内容（富文本），需要根据内容先计算cell高度，然后发现在cellWillAppear()中无法准确获取cell的宽度，进而导致无法计算文字高度，在cellDidDisappear()可以获取cell宽度，但是对item.cellHeight赋值并执行item.updateHeight()没有生效

**Comment by jzhang0480** [comment]
在cellWillAppear()获取cell宽度，可以通过获取self.item.tableViewManager.tableView的宽度就是cell的宽度。
cellWillAppear()等价于tableView(_:cellForRowAt:)方法，在每一个cell出现在屏幕里时都会调用，这里写计算高度更新高度的方法会有问题。计算高度应该在初始化item的时候就计算好。
要是还有问题的话提供下demo，我帮你看一下: )
