### ISSUE TITLE
大佬,这个树状的tableView要怎么往里面添加数据啊

### ISSUE THREAD

**Issue by ydstar** [JavenZ/ZJTableViewManager#3]
大佬,这个树状的tableView要怎么往里面添加数据啊

**Comment by jzhang0480** [comment]
以Level0Cell为例，你给Level0CellItem加一个属性比如说string。然后在Level0Cell里面重写cellWillAppear方法，取到cell的item属性，赋值就行了。参考一下项目里另外的demo比较直观。
