### ISSUE TITLE
你好，请问该框架没有滚动事件穿透吗？

### ISSUE THREAD

**Issue by trembleCat** [JavenZ/ZJTableViewManager#4]
你好，最近遇到一个项目需要用ScrollView嵌套TableView，使用了项目中的ExpandTree功能。
然后发现在滚动scrollView时不能对TableView进行滚动，重写了ScrollView中的Simultaneously返回True也不行，请问是我写的有问题吗？还请指导一下，谢谢。

**Comment by jzhang0480** [comment]
sorry，最近没关注邮箱。滚动scrollView的同时滚动TableView？这是什么需求，感觉很奇怪。ps：ExpandTree近期做了优化，降低了使用时的代码量，提升了扩展性，版本1.0.3-beta。
