### ISSUE TITLE
第0级第一条数据是展开的，在点击第0级第二条数据展开时，第一条数据自动收起，有这个功能吗

### ISSUE THREAD

**Issue by zlx416** [JavenZ/ZJTableViewManager#6]

**Comment by jzhang0480** [comment]
下载最新的demo，`ExpandTreeViewController`文件里面第42行`item0.isAutoClose = true`注释打开。感兴趣可以看看`isAutoClose`的实现，拓展相关的功能都可以用同样的思路。
`pod 'ZJTableViewManager', '~> 1.0.6-beta'`
