### ISSUE TITLE
三级列表选中问题

### ISSUE THREAD

**Issue by Shameless521** [JavenZ/ZJTableViewManager#7]
三级列表中，在第三级需要有单选的功能，但是我在实现的时候，无法刷新页面数据，不知道为啥。麻烦大神帮忙看下。下面是代码
`for item in linelistModel! {
            let item0 = ServerListTitleItem()
            item0.model = item
            item0.isExpand = true
            item0.cellHeight = SXRealValue(55)
            section.add(item: item0)
            
            for group in item.groupList! {
                let item1 = ServerVideoItem()
                item1.model = group
                item1.cellHeight = SXRealValue(60)
                item0.addSub(item: item1, section: section)

                for vm in group.vmList! {
                    let item2 = ServerContentItem()
                    item2.model = vm
                    if vmess.flagId == self.selectModel?.flagId {
                        item2.isSelect = true
                        item1.isExpand = true
                    }else {
                        item2.isSelect = false
                        item1.isExpand = false
                    }
                    item2.cellHeight = SXRealValue(55)
                    item1.addSub(item: item2, section: section)
                    
                    item2.setSelectionHandler { (Model: ServerContentItem) in                      
                        self.selectModel = vmessModel.model
                        self.manager.reload()
                    }
                }
            }
        }`

**Comment by jzhang0480** [comment]
如果你是和我demo里面一样，用的`override func setSelected(_ selected: Bool, animated: Bool) {}`方法实现的单选，那你
需要加一行`item2.selectionStyle = .default`, 并且去掉setSelectionHandler回调里面的`self.manager.reload()`
原因是ZJExpandTreeCellItem类里面默认把选中效果关掉了。不需要reload()的原因是这是系统的选中方法，系统有实现，不需要自己手动刷新tableView。

**Comment by Shameless521** [comment]
我按照您的方法试了一下，没有打到预期的效果，可能是我的写的不对，你看我用自己的理解写了一下，但是有一个问题，选中完三级以后，我想吧二级展开，但是这种情况下，展开是有问题的，麻烦您帮我看下。

   ```
 func setShowData() {
        manager.add(section: section)

        guard let listModel = self.model else {
            return
        }
        
        let linelistModel = listModel.resultLineInfo

        for item in linelistModel! {
            let item0 = ServerListTitleItem()
            item0.model = item
            item0.isExpand = true
            item0.cellHeight = SXRealValue(55)
            section.add(item: item0)
            
            for group in item.groupList! {
                let item1 = ServerVideoItem()
                item1.model = group
                item1.cellHeight = SXRealValue(60)
                item0.addSub(item: item1, section: section)

                for vmess in group.vmessList! {
                    let item2 = ServerContentItem()
                    item2.model = vmess
                    if vmess.flagId == self.selectModel?.flagId {
                        item2.isSelect = true
                    }else {
                        item2.isSelect = false
                    }

                    item2.cellHeight = SXRealValue(55)
                    item1.addSub(item: item2, section: section)
                    
                    item2.setSelectionHandler { (vmessModel: ServerContentItem) in
                        
                        self.selectModel = vmessModel.model
                        self.section.removeAllItems()
                        self.manager.removeAllSections()
                        self.setShowData()
                    }
                }
            }
        }
        
        manager.reload()
    }
```

**Comment by Shameless521** [comment]
> 如果你是和我demo里面一样，用的`override func setSelected(_ selected: Bool, animated: Bool) {}`方法实现的单选，那你
> 需要加一行`item2.selectionStyle = .default`, 并且去掉setSelectionHandler回调里面的`self.manager.reload()`
> 原因是ZJExpandTreeCellItem类里面默认把选中效果关掉了。不需要reload()的原因是这是系统的选中方法，系统有实现，不需要自己手动刷新tableView。

我刚才用您的方法试了一下，有效果，但是在点击二级的时候，三级的选中效果会失效，不知道是什么原因。而且没有默认的选中效果。

**Comment by jzhang0480** [comment]
哦，这个我没考虑到，这个应该是系统的方法的缺陷了。我看你一开始提供的代码，isSelect属性应该是你自己定义的吧，然后在cell里面根据isSelect显示不同的样式。那还是用你自定义的选中方法吧，再有问题的话最好提供个简化的demo
```swift
                item2.setSelectionHandler { (vmessModel: ServerContentItem) in    
                    // 找出当前同级的所有cell选中状态设置为false
                    let sameLevelItems = vmessModel.superLevelItem?.getAllBelowItems().filter({$0.level == vmessModel.level})
                    for item in sameLevelItems! {
                            item.isSelect = false
                    }                  
                    vmessModel. isSelect = true//当前点击中的cell选中状态设置为true
                    self.selectModel = vmessModel.model
                    self.manager.reload()
                }
```

**Comment by Shameless521** [comment]
> 哦，这个我没考虑到，这个应该是系统的方法的缺陷了。我看你一开始提供的代码，isSelect属性应该是你自己定义的吧，然后在cell里面根据isSelect显示不同的样式。那还是用你自定义的选中方法吧，再有问题的话最好提供个简化的demo
> 
> ```swift
>                 item2.setSelectionHandler { (vmessModel: ServerContentItem) in    
>                     // 找出当前同级的所有cell选中状态设置为false
>                     let sameLevelItems = vmessModel.superLevelItem?.getAllBelowItems().filter({$0.level == vmessModel.level})
>                     for item in sameLevelItems! {
>                             item.isSelect = false
>                     }                  
>                     vmessModel. isSelect = true//当前点击中的cell选中状态设置为true
>                     self.selectModel = vmessModel.model
>                     self.manager.reload()
>                 }
> ```

其实最关键的就是页面数据没有刷新，如果方便的化，能给我一个联系方式么，我给您demo

**Comment by jzhang0480** [comment]
就用你最初提问的时候的代码，在`item2.setSelectionHandler`里面按照我前一个回复改一下应该就行了。还是不行的话，你demo发我邮箱吧jzhang0480@outlook.com

**Comment by Shameless521** [comment]
> 就用你最初提问的时候的代码，在`item2.setSelectionHandler`里面按照我前一个回复改一下应该就行了。还是不行的话，你demo发我邮箱吧[jzhang0480@outlook.com](mailto:jzhang0480@outlook.com)

刚试了一下，还是不行，我已经把简易demo发您邮箱了，麻烦您了

**Comment by jzhang0480** [comment]
你说还是不行，但是没说具体问题。我看了一下你的demo，我猜你说不行的原因是现在只在单击的那个cell所在的展开区域内有效。如果需要在整个tableview范围内实现单选，那就把
`let sameLevelItems = vmessModel.superLevelItem?.getAllBelowItems().filter({$0.level == vmessModel.level})`
改成
`let sameLevelItems = self.section.items.filter({($0 as! ZJExpandTreeCellItem).level == vmessModel.level})`

**Comment by Shameless521** [comment]
> 你说还是不行，但是没说具体问题。我看了一下你的demo，我猜你说不行的原因是现在只在单击的那个cell所在的展开区域内有效。如果需要在整个tableview范围内实现单选，那就把
> `let sameLevelItems = vmessModel.superLevelItem?.getAllBelowItems().filter({$0.level == vmessModel.level})`
> 改成
> `let sameLevelItems = self.section.items.filter({($0 as! ZJExpandTreeCellItem).level == vmessModel.level})`

非常感谢，这个问题解决了，但是还有一个问题。第一次进来，默认会有问题。
![Simulator Screen Shot - iPhone Xʀ - 2020-07-05 at 18 21 16](https://user-images.githubusercontent.com/25836080/86530573-5cff0e80-beec-11ea-9d7f-d205500a838e.png)
![Simulator Screen Shot - iPhone Xʀ - 2020-07-05 at 18 21 17](https://user-images.githubusercontent.com/25836080/86530575-5ff9ff00-beec-11ea-9140-a1d4eb91054c.png)

**Comment by jzhang0480** [comment]
这个应该是你设置默认的isselect=true的时候出问题导致的，断点调试一下吧。
