### ISSUE TITLE
autoHeight后约束报错

### ISSUE THREAD

**Issue by narakai** [JavenZ/ZJTableViewManager#8]
xib上设置上下左右约束且显示约束没问题，autoHeight后manager.reload报约束错误。不调用autoHeight不报错误，但是撑不开

**Comment by jzhang0480** [comment]
1. autoHeight内部调用的是系统的方法，算出来的高度如果导致约束冲突，理论上就是约束存在问题。把cellHeight设置成UITableView.automaticDimension，让系统自动处理高度试一下，应该也会有同样的错误。
2. 因为看不到具体布局，按经验建议尝试通过修改报错的约束的Priority解决。

ps. 如果改成automaticDimension就不报错了，方便的话提供个demo给我研究下: )
jzhang0480@outlook.com

**Comment by narakai** [comment]
改成automaticDimension是正常的，demo等我整理一下吧

**Comment by jzhang0480** [comment]
不好意思，今天才看你发的代码，原因是因为`item.autoHeight()`是提前计算高度，demo里面用snapkit设置约束，导致在调用`item.autoHeight()`的时候tableView本身的width还是不确定的，所以计算出来的高度也就不对了。系统automaticDimension计算高度是实时的，所以就没问题。

解决办法是提前先设置一下tableView的width(比如在`viewDidLoad`最前面写上`tableView.frame = view.bounds`)

**Comment by narakai** [comment]
好的，谢谢解答
