### ISSUE TITLE
pod引入后toggleExpand方法报错

### ISSUE THREAD

**Issue by narakai** [JavenZ/ZJTableViewManager#9]
应该是权限问题，Overriding non-open instance method outside of its defining module

**Comment by jzhang0480** [comment]
发现部分代码没有更新到pod上，刚刚更新了一下，`pod 'ZJTableViewManager', '~> 1.0.6'`就可以了，搜不到的话pod repo update一下。更新完`ZJCelltemClass`会报错，全局替换成`ZJCellItemClass`就好了，低级的拼写错误，尴尬。

**Comment by narakai** [comment]
好的，辛苦了
